# Generated by Django 2.2.6 on 2019-12-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=40)),
                ('motivation_letter', models.TextField(max_length=200)),
                ('is_accepted', models.BooleanField(default=False)),
                ('photo', models.FileField(upload_to='static/applicant_photos')),
            ],
        ),
    ]
