# Generated by Django 2.2.6 on 2019-12-07 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0002_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='birth_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
