# Generated by Django 2.2.6 on 2019-12-07 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0004_remove_applicant_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='birth_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
