# Generated by Django 2.2.6 on 2019-12-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0005_applicant_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='birth_date',
            field=models.DateTimeField(),
        ),
    ]
