# Generated by Django 2.2.6 on 2019-12-07 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0007_auto_20191207_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='applicant',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ccapp.ApplicantStatus'),
            preserve_default=False,
        ),
    ]
