# Generated by Django 2.2.6 on 2019-12-07 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0010_auto_20191207_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicantstatus',
            options={'verbose_name_plural': 'Applicant Statuses'},
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='ccapp.ApplicantStatus'),
        ),
    ]
