# Generated by Django 2.2.6 on 2019-12-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0012_applicant_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='photo',
            field=models.FileField(blank=True, upload_to='static/applicant_photos'),
        ),
    ]
