# Generated by Django 2.2.6 on 2019-12-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0014_remove_applicant_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(max_length=200)),
                ('sender_name', models.CharField(max_length=30)),
                ('sender_email', models.CharField(max_length=50)),
            ],
        ),
    ]
